export const GET_BOOKS_CACHE = 'GET_BOOKS_CACHE';
export const GET_BOOK_DETAIL_CACHE = 'GET_BOOK_DETAIL_CACHE';
export const GET_REPORT_SELES_CACHE = 'GET_REPORT_SELES_CACHE';
export const GET_ADMIN_TRANSACTIONS_CACHE = 'GET_ADMIN_TRANSACTIONS_CACHE';
export const GET_ADMIN_TRANSACTIONS_DETAIL_CACHE =
  'GET_ADMIN_TRANSACTIONS_DETAIL_CACHE';
