GET http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmNzY5MzA5YS04NzZlLTQ5NDQtYWEwMi1kMmIwNDBmOWIyYzYiLCJlbWFpbCI6Im1hcmthc0BleGFtcGxlLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImp0aSI6ImM2YTA2YTIwLWFkYmUtNDU1Zi04ZjY0LTFkZmUyMTU3YTI2OSIsImlhdCI6MTc2MzMwMjI0MSwiZXhwIjoxNzYzMzA1ODQxfQ.rb9-S7DmvqNnqq_0WsyF00EEAQEGkWW85i-low2mH0U